//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BarberShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationsSet
    {
        public int Id { get; set; }
        public int IdWorker { get; set; }
        public int IdClent { get; set; }
        public int IdService { get; set; }
        public long Price { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual WorkersSet WorkersSet { get; set; }
        public virtual ServicesSet ServicesSet { get; set; }
    }
}
